#!/bin/bash
echo Usage: autobackup \<source\> \<destination folder\> \<timeout\>
SRC="$1"
DST="$2"
TIME="$3"
DATEARGS="+%Y-%m-%d %H:%M"
if [[ -d "$SRC" ]]; then #is it a folder or a file?
	echo Src is a folder
elif [[ -f "$SRC" ]]; then
	echo Src is a file
else
	echo Source is not a folder or a file!
	exit 1
fi


if [[ ! -d "$DST" ]]; then #is destination a real directory?

	echo Destination folder is not a directory!
	if ! [[ -f "$DST" ]]; then
		echo Creating directory $DST...
		mkdir $DST
	else
		exit 1;
	fi

fi
RE="^[0-9]+$"
if ! [[ $TIME =~ $RE ]] ; then #is the time a number?
	echo Sleep time \($TIME\) is not a valid number!
	exit 1;
fi

if [[ $TIME < "60" ]]; then
	echo Sleep time is too short! 
	DATEARGS="$DATEARGS:%S"
fi


echo Backup up $SRC to $DST every $TIME seconds.

while [[ 1 == 1 ]]; do #main program loop

OUTFILE=$( date "$DATEARGS" )
OUTFILE="$OUTFILE $SRC"

if [[ -d "$SRC" ]]; then
	mkdir "$DST/$OUTFILE"
	cp -r $SRC "$DST/$OUTFILE"
else
	cp $SRC $DST/$OUTFILE
fi

echo Backed up to $OUTFILE

sleep $TIME

done;
